### ISSUE TITLE
Warning in Ruby 3.0

### ISSUE THREAD

**Issue by thomasklemm** [hopsoft/cable_ready#113]
After upgrading to Ruby 3.0, the following warning gets printed when running system specs right before the first reflex invocation in a spec example:

```
.../ruby/gems/3.0.0/gems/cable_ready-4.5.0/lib/cable_ready/channel.rb:14: 
warning: finalizer references object to be finalized
```

Link to the [line in question](https://github.com/hopsoft/cable_ready/blob/6998860ca753f105c501ee564d8992a99a8e733f/lib/cable_ready/channel.rb#L14).
```
ObjectSpace.define_finalizer self, -> { CableReady.config.delete_observer config_observer }
```

**Comment by marcoroth** [comment]
Hey @thomasklemm, thank you for reporting this issue!

Do you have a clue how that should look like in Ruby 3? I found this Issue in the Ruby Bug tracker which was targeted for Ruby 3.0: https://bugs.ruby-lang.org/issues/5494

But to be honest I don't fully grok what needs to be changed in order to be ready for Ruby 3.

The code was introduced in https://github.com/hopsoft/cable_ready/pull/96. Maybe @hopsoft can expand on it.

**Comment by thomasklemm** [comment]
It looks like the warning gets raised since `self` is being passed to `ObjectSpace.define_finalizer`, according to the [warning  spec'd here](https://github.com/sorah-rbpkg/ruby/blob/5cf6fd89374088e7496d1f517b7697f41aae5725/spec/ruby/core/objectspace/define_finalizer_spec.rb#L63-L78). Not sure what's best for Ruby 3.0.

**Comment by n-rodriguez** [comment]
This might be a solution : https://www.mikeperham.com/2010/02/24/the-trouble-with-ruby-finalizers/

**Comment by leastbad** [comment]
@thomasklemm could you try out the https://github.com/hopsoft/cable_ready/tree/hopsoft/finalize branch from #116 and confirm that it addresses the issues you've seen?

**Comment by alexander-makarenko** [comment]
@leastbad Indeed, https://github.com/hopsoft/cable_ready/pull/116 solves the problem.

**Comment by thomasklemm** [comment]
@leastbad #116 works, the warnings are gone when using the PR branch 👍
